"""initial models

Revision ID: 15fdba873058
Revises: d6dc2881b798
Create Date: 2026-05-07 13:45:53.970802

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "15fdba873058"
down_revision: Union[str, Sequence[str], None] = "d6dc2881b798"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "refresh_token",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "refresh_token",
        "revoked_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.drop_constraint(
        op.f("refresh_token_user_id_fkey"), "refresh_token", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "refresh_token", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("users_name_key"), "users", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("users_name_key"), "users", ["name"], postgresql_nulls_not_distinct=False
    )
    op.drop_constraint(None, "refresh_token", type_="foreignkey")
    op.create_foreign_key(
        op.f("refresh_token_user_id_fkey"),
        "refresh_token",
        "users",
        ["user_id"],
        ["id"],
    )
    op.alter_column(
        "refresh_token",
        "revoked_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "refresh_token",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
