"""initial models

Revision ID: 9508b4709b60
Revises: 073205162684
Create Date: 2026-04-27 20:31:10.729920

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "9508b4709b60"
down_revision: Union[str, Sequence[str], None] = "073205162684"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
