"""initial models

Revision ID: bec6e28dfc72
Revises: 8c4b09067751
Create Date: 2026-04-26 23:41:51.896210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bec6e28dfc72'
down_revision: Union[str, Sequence[str], None] = '8c4b09067751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contest', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('contest', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('solution', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('solution', 'task_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('solution', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('solution', 'status',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.add_column('task', sa.Column('test', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.alter_column('task', 'contest_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('task', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('task', 'task_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('task', 'test_file_path')
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('user', 'login',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('user', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'user'::character varying"))
    op.alter_column('user', 'password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('user', 'login',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('user', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.add_column('task', sa.Column('test_file_path', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.alter_column('task', 'task_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('task', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('task', 'contest_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('task', 'test')
    op.alter_column('solution', 'status',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('solution', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('solution', 'task_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('solution', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('contest', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('contest', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
